[project]
name = "pd2af"
dynamic = ["version"]
description = "Transform process-description maps (SBGN-PD, CellDesigner) into SBGN-AF activity-flow maps"
authors = [{ name = "Adrien Rougny", email = "adrien.rougny@uni.lu" }]
readme = "README.md"
requires-python = ">=3.12"
license = { text = "GPL-3.0-or-later" }
dependencies = [
  "aspcompose>=0.1.0",
  "clorm>=1.6.3",
  "momapy>=0.14.0",
  "momapy-kb[clingo]>=0.5.0",
  "pydot>=4.0.1",
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/adrienrougny/pd2af"
Issues = "https://github.com/adrienrougny/pd2af/issues"
Documentation = "https://adrienrougny.github.io/pd2af/"

[project.scripts]
pd2af = "pd2af.cli:main"

[dependency-groups]
dev = [
  "mkdocs-material>=9.7.7",
  "mkdocs-gen-files>=0.6.1",
  "mkdocstrings-python>=2.0.7",
  "griffe-fieldz>=0.5.0",
  "griffe-inherited-docstrings>=1.1.3",
  "mkdocs-pygments>=0.1.0",
  "ruff>=0.14.10,<0.15",
  "pre-commit>=4.5.1",
  "git-cliff>=2.12.0",
  { include-group = "test" },
]
test = ["pytest>=9.1.1", "pytest-cov>=6.0.0"]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
tag_regex = '^v(?P<version>([0-9].*))'

[tool.hatch.build.targets.wheel]
packages = ["src/pd2af"]

[tool.ruff.lint]
extend-select = ["D", "ANN"]
ignore = ["ANN401", "ANN002", "ANN003"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true
mypy-init-return = true
suppress-none-returning = true

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["D", "ANN"]
"docs/**" = ["D", "ANN"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-ra"

[tool.coverage.run]
source = ["src/pd2af"]
branch = true

[tool.coverage.report]
show_missing = true
skip_covered = false
fail_under = 70
