[project]
name = "pd2af"
version = "0.0.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "aspcompose",
  "casq>=1.4.3",
  "clorm>=1.6.1",
  "momapy-kb",
  "momapy[skia]>=0.2.7",
  "pydot>=4.0.1",
]

[project.scripts]
pd2af = "pd2af.cli:main"

[project.optional-dependencies]
test = ["pytest>=7"]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
test = ["pytest>=7"]

[tool.uv.sources]
momapy-kb = { path = "../momapy_kb", editable = true }
aspcompose = { path = "../aspcompose", editable = true }

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-ra"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
