[project]
name = "pd2af"
version = "0.0.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "casq>=1.4.3",
  "clorm>=1.6.1",
  "momapy-kb",
  "momapy[skia]>=0.2.7",
  "pydot>=4.0.1",
]

[tool.uv.sources]
momapy-kb = { path = "../momapy_kb", editable = true }
